#!/usr/bin/env python3
"""render_triage_review_packet.py — generate the ADR-PIPE-006 independent
triage-review packet from the spine, never from prose.

WHY THIS IS A GENERATOR AND NOT A WRITTEN DOCUMENT. ADR-PIPE-006 requires an
INDEPENDENT REVIEW OF TRIAGE. The reviewer has to judge 57 classifications
that Claude produced, which means the packet they read must be the authority's
own content rather than the author's later summary of it. Everything here is
read from `queue_items` and from the `queue_item_events` rows the triage wrote;
the only text this file contributes is headers and the explicit statements of
what each section is. If a classification or its evidence is changed in the
spine, re-running this changes the packet; the packet cannot drift into being
a nicer account of the triage than the audit trail supports.

WHAT IT DOES NOT DO. It writes no spine row, mutates nothing, and reaches the
database read-only. It also does not render a verdict: ADR-PIPE-006's review is
the reviewer's act, and a packet that pre-filled an outcome would be the author
reviewing their own work.

The hand-written half of the packet is QUESTION_FOR_CHATGPT.md, which carries
the review contract and is marked as hand-written there. This file owns only
the generated evidence files, each of which says so in its first line.

    python3 tools/queue/render_triage_review_packet.py            # write
    python3 tools/queue/render_triage_review_packet.py --verify   # exit 1 if stale
"""
import argparse
import json
import os
import sqlite3
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
DEFAULT_DB = os.environ.get("CIS_SPINE_PATH", os.path.join(ROOT, "data", "cis_memory.db"))
OUT_DIR = os.path.join(ROOT, "docs", "review_packets", "ADR-PIPE-006-TRIAGE-REVIEW")

# The triage pass identified itself in every row it wrote. The population is
# derived from that attribution rather than from a hardcoded list of 57 item
# numbers, so the packet cannot claim coverage the audit trail does not show.
TRIAGE_ACTOR_PREFIX = "formal-queue-triage-"

GENERATED_BANNER = (
    "<!-- GENERATED by tools/queue/render_triage_review_packet.py from the spine. "
    "DO NOT EDIT. Every classification, evidence block and rationale below is the "
    "verbatim content of a queue_item_events row written by the triage pass. -->"
)


def connect(db_path):
    conn = sqlite3.connect("file:%s?mode=ro" % db_path, uri=True)
    conn.row_factory = sqlite3.Row
    return conn


def item_sort_key(item_num):
    tier, _, rest = item_num.partition(".")
    try:
        return (int(tier), float(rest))
    except ValueError:
        return (9999, 0.0)


def triage_population(conn):
    """The 57 rows, each with its final classification and the two events that
    wrote it. Evidence and note are IDENTICAL on an item's need_status and
    scope events because queue_set.py was invoked once per item with both
    flags; that is asserted here rather than assumed, and a divergence is
    reported into the packet instead of being silently collapsed."""
    rows = conn.execute(
        "SELECT item_num, field, old_value, new_value, changed_at, changed_by, "
        "       evidence, note "
        "FROM queue_item_events WHERE changed_by LIKE ? || '%'",
        (TRIAGE_ACTOR_PREFIX,),
    ).fetchall()

    items = {}
    for r in rows:
        rec = items.setdefault(r["item_num"], {"events": {}})
        rec["events"][r["field"]] = dict(r)

    for item_num, rec in items.items():
        ev = rec["events"]
        need, scope = ev.get("need_status"), ev.get("scope")
        rec["evidence_divergence"] = None
        if need and scope:
            if (need["evidence"] or "") != (scope["evidence"] or ""):
                rec["evidence_divergence"] = "evidence differs between the need_status and scope events"
            elif (need["note"] or "") != (scope["note"] or ""):
                rec["evidence_divergence"] = "note differs between the need_status and scope events"
        row = conn.execute(
            "SELECT item_num, tier, title, body_md, form, scope, need_status, "
            "       need_raw, check_class, status_changed_at, status_changed_by "
            "FROM queue_items WHERE item_num=?", (item_num,)).fetchone()
        rec["item"] = dict(row) if row else None
    return items


def residual_rows(conn):
    """Rows carrying one classification field but not the other. ADR-PIPE-001
    and ADR-PIPE-006 bound the triage pass to rows carrying NEITHER field, so
    these were never in the population. They are published so the reviewer can
    see them and see that they are excluded, not so they can be reviewed as
    triage output."""
    return [dict(r) for r in conn.execute(
        "SELECT item_num, tier, title, scope, need_status, status_changed_at, "
        "       status_changed_by "
        "FROM queue_items "
        "WHERE (scope IS NULL OR scope='') != (need_status IS NULL OR need_status='') "
        "ORDER BY tier, item_num")]


def queue_integrity(conn):
    def one(sql):
        return conn.execute(sql).fetchone()[0]
    return {
        "queue_items": one("SELECT COUNT(*) FROM queue_items"),
        "queue_edges": one("SELECT COUNT(*) FROM queue_edges"),
        "awaiting_triage": one(
            "SELECT COUNT(*) FROM queue_items WHERE (scope IS NULL OR scope='') "
            "AND (need_status IS NULL OR need_status='')"),
        "fully_classified": one(
            "SELECT COUNT(*) FROM queue_items WHERE scope IS NOT NULL AND scope<>'' "
            "AND need_status IS NOT NULL AND need_status<>''"),
        "partially_classified": one(
            "SELECT COUNT(*) FROM queue_items "
            "WHERE (scope IS NULL OR scope='') != (need_status IS NULL OR need_status='')"),
        "triage_events": one(
            "SELECT COUNT(*) FROM queue_item_events WHERE changed_by LIKE '%s%%'"
            % TRIAGE_ACTOR_PREFIX),
        "triage_items": one(
            "SELECT COUNT(DISTINCT item_num) FROM queue_item_events "
            "WHERE changed_by LIKE '%s%%'" % TRIAGE_ACTOR_PREFIX),
    }


def common_note_prefix(items):
    """The provenance paragraph every one of the 57 notes opens with, found by
    comparison rather than declared, so the packet can hoist it once and show
    only each item's own reasoning underneath. Returned with the count of rows
    that carry it, because a prefix present on 56 of 57 would be a finding."""
    notes = [rec["events"]["need_status"]["note"] or ""
             for rec in items.values() if "need_status" in rec["events"]]
    if not notes:
        return "", 0
    prefix = notes[0]
    for note in notes[1:]:
        limit = min(len(prefix), len(note))
        i = 0
        while i < limit and prefix[i] == note[i]:
            i += 1
        prefix = prefix[:i]
    # Cut back to the last paragraph break so the hoisted text is whole
    # sentences rather than a truncation artefact.
    cut = prefix.rfind("\n\n")
    if cut > 0:
        prefix = prefix[:cut]
    carriers = sum(1 for n in notes if n.startswith(prefix)) if prefix else 0
    return prefix, carriers


def fence(text, lang=""):
    """Fence content whose own backticks would otherwise close the block."""
    body = text.rstrip("\n")
    ticks = "```"
    while ticks in body:
        ticks += "`"
    return "%s%s\n%s\n%s" % (ticks, lang, body, ticks)


def render_index(items, integrity, residual, prefix_carriers):
    order = sorted(items, key=item_sort_key)
    out = [GENERATED_BANNER, "", "# ADR-PIPE-006 triage review — index of the population under review", ""]
    out.append("Derived from `queue_item_events` rows attributed to "
               "`%s*`. The population is whatever carries that attribution; it is "
               "not a list typed into this file." % TRIAGE_ACTOR_PREFIX)
    out.append("")
    out.append("| measure | value |")
    out.append("|---|---|")
    out.append("| items under review | %d |" % integrity["triage_items"])
    out.append("| classification events written by the pass | %d |" % integrity["triage_events"])
    out.append("| queue_items total | %d |" % integrity["queue_items"])
    out.append("| awaiting triage now | %d |" % integrity["awaiting_triage"])
    out.append("| fully classified now | %d |" % integrity["fully_classified"])
    out.append("| partially classified now (NOT under review) | %d |" % integrity["partially_classified"])
    out.append("| queue_edges | %d |" % integrity["queue_edges"])
    out.append("| of %d notes carrying the shared provenance paragraph | %d |"
               % (integrity["triage_items"], prefix_carriers))
    out.append("")

    by_status = {}
    by_token = {}
    for item_num in order:
        it = items[item_num]["item"]
        by_status[it["need_status"]] = by_status.get(it["need_status"], 0) + 1
        token = (it["scope"] or "").split(" ")[0].split("—")[0].strip() or "(none)"
        by_token[token] = by_token.get(token, 0) + 1
    out.append("## Distribution of the values under review")
    out.append("")
    out.append("`need_status`: " + ", ".join(
        "%s %d" % (k, v) for k, v in sorted(by_status.items(), key=lambda kv: -kv[1])))
    out.append("")
    out.append("`scope` leading token: " + ", ".join(
        "%s %d" % (k, v) for k, v in sorted(by_token.items(), key=lambda kv: -kv[1])))
    out.append("")
    out.append("## One line per item")
    out.append("")
    out.append("Pre-triage state was `scope` NULL and `need_status` NULL on every "
               "row — that is what made it the population. The `old_value` column "
               "of both events is published per item in the tier files so this can "
               "be checked rather than taken on trust.")
    out.append("")
    out.append("| item | tier | title | pre-triage | final need_status | final scope |")
    out.append("|---|---|---|---|---|---|")
    for item_num in order:
        it = items[item_num]["item"]
        ev = items[item_num]["events"]
        pre_need = ev["need_status"]["old_value"]
        pre_scope = ev["scope"]["old_value"]
        pre = "both NULL" if not pre_need and not pre_scope else (
            "need=%r scope=%r" % (pre_need, pre_scope))
        title = (it["title"] or "").replace("|", "\\|")
        scope = (it["scope"] or "").replace("|", "\\|")
        out.append("| `%s` | %d | %s | %s | `%s` | %s |"
                   % (item_num, it["tier"], title, pre, it["need_status"], scope))
    out.append("")
    out.append("## Rows deliberately excluded from this population")
    out.append("")
    out.append("%d rows carry one classification field and not the other. They were "
               "never in the triage population and are NOT reviewed triage output. "
               "They are published in `RESIDUAL_PARTIAL_ROWS.md` so their exclusion "
               "is visible rather than quiet." % len(residual))
    out.append("")
    return "\n".join(out) + "\n"


def render_tier(tier, items, shared_prefix):
    order = [n for n in sorted(items, key=item_sort_key)
             if items[n]["item"]["tier"] == tier]
    out = [GENERATED_BANNER, "",
           "# ADR-PIPE-006 triage review — Tier %d (%d items)" % (tier, len(order)), ""]
    out.append("Each item below carries, in this order: the final two "
               "classification values, the `old_value` both events recorded as the "
               "pre-triage state, the measured evidence the classification rests "
               "on, the item-specific rationale, and the item's own authoritative "
               "text. The shared provenance paragraph common to all 57 notes is "
               "hoisted into `QUESTION_FOR_CHATGPT.md` and not repeated per item.")
    out.append("")
    for item_num in order:
        rec = items[item_num]
        it, ev = rec["item"], rec["events"]
        need, scope = ev["need_status"], ev["scope"]
        out.append("---")
        out.append("")
        out.append("## `%s` — %s" % (item_num, it["title"]))
        out.append("")
        out.append("| field | pre-triage | final |")
        out.append("|---|---|---|")
        out.append("| `need_status` | %s | **`%s`** |"
                   % ("NULL" if not need["old_value"] else "`%s`" % need["old_value"],
                      need["new_value"]))
        out.append("| `scope` | %s | **%s** |"
                   % ("NULL" if not scope["old_value"] else "`%s`" % scope["old_value"],
                      (scope["new_value"] or "").replace("|", "\\|")))
        out.append("")
        out.append("Written %s by `%s`. `check_class` on the row: %s. "
                   "`need_raw`: %s."
                   % (need["changed_at"], need["changed_by"],
                      it["check_class"] or "NULL",
                      ("%r" % it["need_raw"]) if it["need_raw"] else "NULL"))
        if rec["evidence_divergence"]:
            out.append("")
            out.append("**PACKET FINDING — %s.** The two events for this item do not "
                       "carry the same justification, which the single-invocation "
                       "write path should have made impossible. Both are printed "
                       "below." % rec["evidence_divergence"])
        out.append("")
        out.append("### Measured evidence")
        out.append("")
        out.append(fence(need["evidence"] or "(no evidence recorded)"))
        out.append("")
        if rec["evidence_divergence"] == "evidence differs between the need_status and scope events":
            out.append("### Measured evidence recorded on the `scope` event instead")
            out.append("")
            out.append(fence(scope["evidence"] or "(no evidence recorded)"))
            out.append("")
        out.append("### Rationale recorded with the write")
        out.append("")
        note = need["note"] or ""
        if shared_prefix and note.startswith(shared_prefix):
            note = note[len(shared_prefix):].lstrip("\n")
            out.append("*(shared provenance paragraph omitted — see "
                       "`QUESTION_FOR_CHATGPT.md` §Provenance)*")
            out.append("")
        out.append(fence(note or "(no item-specific rationale recorded)"))
        out.append("")
        if rec["evidence_divergence"] == "note differs between the need_status and scope events":
            out.append("### Rationale recorded on the `scope` event instead")
            out.append("")
            out.append(fence(scope["note"] or "(none)"))
            out.append("")
        out.append("### The item's own authoritative text")
        out.append("")
        out.append("This is `queue_items.body_md`, the text the classification must "
                   "not contradict. It is the author's prose, not the triage's.")
        out.append("")
        out.append(fence(it["body_md"] or "(empty)", "markdown"))
        out.append("")
    return "\n".join(out) + "\n"


def render_residual(residual, integrity):
    out = [GENERATED_BANNER, "",
           "# Rows that are NOT part of the reviewed triage population", ""]
    out.append("**These %d rows are not triage output and must not be read as "
               "reviewed classifications.** ADR-PIPE-001 defines the triage pass "
               "over the rows that carry NEITHER `scope` nor `need_status`; "
               "ADR-PIPE-006 bounds the pass and forbids item redesign inside it. "
               "Each row below already carried one of the two fields before the "
               "pass began, so including it would have widened the population "
               "beyond the authorized definition." % len(residual))
    out.append("")
    out.append("They report as PARTIALLY CLASSIFIED. The queue's own counters "
               "publish `awaiting triage %d` and `fully classified %d` side by "
               "side for exactly this reason: neither number on its own can be "
               "read as 'triage complete'."
               % (integrity["awaiting_triage"], integrity["fully_classified"]))
    out.append("")
    out.append("| item | tier | title | need_status | scope | last status change |")
    out.append("|---|---|---|---|---|---|")
    for r in residual:
        out.append("| `%s` | %s | %s | `%s` | %s | %s |" % (
            r["item_num"], r["tier"], (r["title"] or "").replace("|", "\\|"),
            r["need_status"] or "NULL",
            "NULL" if not r["scope"] else (r["scope"] or "").replace("|", "\\|"),
            r["status_changed_at"] or "—"))
    out.append("")
    out.append("Completing these is a separate scopeable decision. Six of them "
               "(4.20, 4.28–4.32) are the rows whose `scope` ADR-PIPE-009 proved "
               "the old recovery path fabricated out of wrapped prose; their NULL "
               "is the honest value a human chose, and ADR-PIPE-009 clause 9 "
               "forbids cleaning the related legacy integrity debt.")
    out.append("")
    return "\n".join(out) + "\n"


def build(db_path):
    conn = connect(db_path)
    try:
        items = triage_population(conn)
        integrity = queue_integrity(conn)
        residual = residual_rows(conn)
    finally:
        conn.close()
    missing = [n for n, rec in items.items() if rec["item"] is None]
    if missing:
        raise SystemExit("triage events exist for rows absent from queue_items: %s"
                         % ", ".join(sorted(missing)))
    shared_prefix, carriers = common_note_prefix(items)
    files = {"INDEX.md": render_index(items, integrity, residual, carriers),
             "RESIDUAL_PARTIAL_ROWS.md": render_residual(residual, integrity)}
    for tier in sorted({rec["item"]["tier"] for rec in items.values()}):
        files["CLASSIFICATIONS_TIER_%d.md" % tier] = render_tier(tier, items, shared_prefix)
    meta = {"shared_note_prefix": shared_prefix,
            "shared_note_prefix_carriers": carriers,
            "integrity": integrity}
    return files, meta


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--db", default=DEFAULT_DB)
    ap.add_argument("--out", default=OUT_DIR)
    ap.add_argument("--verify", action="store_true",
                    help="exit 1 if any generated file differs from the spine")
    ap.add_argument("--print-shared-prefix", action="store_true")
    a = ap.parse_args()

    files, meta = build(a.db)
    if a.print_shared_prefix:
        print(meta["shared_note_prefix"])
        return 0

    if a.verify:
        stale = []
        for name, content in sorted(files.items()):
            path = os.path.join(a.out, name)
            if not os.path.exists(path):
                stale.append("%s: missing" % name)
            else:
                with open(path, encoding="utf-8") as fh:
                    if fh.read() != content:
                        stale.append("%s: differs from the spine" % name)
        if stale:
            print("STALE")
            for s in stale:
                print("  " + s)
            return 1
        print("fresh — %d generated files match the spine" % len(files))
        print(json.dumps(meta["integrity"], indent=2))
        return 0

    os.makedirs(a.out, exist_ok=True)
    for name, content in sorted(files.items()):
        with open(os.path.join(a.out, name), "w", encoding="utf-8") as fh:
            fh.write(content)
        print("wrote %-32s %7d bytes" % (name, len(content.encode("utf-8"))))
    print(json.dumps(meta["integrity"], indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
